default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: web_entities_development
  username: postgres
  password: 123456789
  host: localhost

production:
  <<: *default
  database: web_entities_production
  username: <%= ENV["DB_PRODUCTION_USERNAME"] %>
  password: <%= ENV["DB_PRODUCTION_PASSWORD"] %>
  host: <%= ENV["DB_PRODUCTION_HOST"] %>
